### ISSUE TITLE
Do you presently have predefined layouts similar to tmuxinator in tmux?

### ISSUE THREAD

**Issue by megalithic** [kitten/nix-system#1]
https://github.com/kitten/nix-system/blob/f1c0fe91eb4365d81527a736cd10d9d7ce865b3c/config/scripts/wezmux.sh#L82

God day @kitten; I was wondering, with this setup, if you also have predefined layouts for each "session", similar to tmux sessions and tmuxinator layouts?

**Comment by kitten** [comment]
Sorry, I must've overlooked the original notification for this 😅 
I know it's been a while, but also to unfortunately disappoint you, I haven't really been using this script anymore, and haven't quite updated everything around this workflow just yet. That said, I also don't use any predefined layouts, not even in Tmux. It simply isn't something I'm really interested in, and rather, I either keep sessions going for a while or restore what I need manually, as and in the order I need it in 😅
